---
# tasks file for tftpd
- name: install tftpd
  package:
    name: "{{ tftpd_packages }}"
    state: present
  register: tftpd_install_tftpd
  until: tftpd_install_tftpd is succeeded
  retries: 3

- name: create tfptroot
  file:
    path: "{{ tftpd_tftproot }}"
    state: directory

- name: enable tftpd in xinetd
  template:
    src: tftp.j2
    dest: /etc/xinetd.d/tftp
  notify:
    restart xinetd
