---
# tasks file for tftpd

- name: install tftpd
  package:
    name: "{{ tftpd_packages }}"
    state: present

- name: start and enable tftpd
  service:
    name: "{{ tftpd_service }}"
    state: started
    enabled: yes
