---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    _tftp_directory:
      default: &default /var/lib/tftpboot
      Debian: /srv/tftp
      Ubuntu-18: *default
      Suse: /srv/tftpboot
    tftp_directory: "{{ _tftp_directory[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_tftp_directory[ansible_os_family] | default(_tftp_directory['default'])) }}"
    _tftp_client_package:
      default: tftp
      Debian: atftp
    tftp_client_package: "{{ _tftp_client_package[ansible_os_family] | default(_tftp_client_package['default']) }}"
    _tftp_client_command:
      default: tftp
      Debian: atftp
    tftp_client_command: "{{ _tftp_client_command[ansible_os_family] | default(_tftp_client_command['default']) }}"
    _tftp_test_command:
      default: "{{ tftp_client_command }} localhost -c put /etc/passwd test"
      Debian: "echo \"put /etc/passwd test\" | {{ tftp_client_command }} localhost"
    tftp_test_command: "{{ _tftp_test_command[ansible_os_family] | default(_tftp_test_command['default']) }}"

  tasks:
    - name: Install tftp client
      ansible.builtin.package:
        name: "{{ tftp_client_package }}"
        state: present
      notify:
        - Uninstall tftp client

    - name: Touch tftp_directory/test
      ansible.builtin.file:
        path: "{{ tftp_directory }}/test"
        mode: "0777"
        state: touch
      notify:
        - Remove test

    - name: Put /etc/passwd to test
      ansible.builtin.shell: "{{ tftp_test_command }}"
      changed_when: true

  handlers:
    - name: Uninstall tftp client
      ansible.builtin.package:
        name: "{{ tftp_client_package }}"
        state: absent

    - name: Remove test
      ansible.builtin.file:
        path: "{{ tftp_directory }}/test"
        state: absent
