---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _tftp_directory:
      default: /var/lib/tftpboo
      Debian: /srv/tftp
    tftp_directory: "{{ _tftp_directory[ansible_os_family] | default(_tftp_directory['default']) }}"

  tasks:
    - name: install tftp client
      package:
        name: tftp
        state: present
      notify:
        - uninstall tftp client

    - name: touch {{ tftp_directory }}/test
      file:
        path: "{{ tftp_directory }}/test"
        mode: "0777"
        state: touch
      notify:
        - remove test

    - name: put /etc/passwd to test
      command: tftp localhost -c put /etc/passwd test

  handlers:
    - name: uninstall tftp client
      package:
        name: tftp
        state: absent

    - name: remove test
      file:
        path: "{{ tftp_directory }}/test"
        state: absent
